export enum CityCategoryEnum {
  Warszawa = 'Warszawa',
  Krakow = 'Kraków',
  Lodz = 'Łódz',
  Wroclaw = 'Wrocław',
  Poznan = 'Poznań',
  Gdansk = 'Gdańsk',
  Sopot = 'Sopot',
  Gdynia = 'Gdynia',
  Szczecin = 'Szczecin',
  Bydgoszcz = 'Bydgoszcz',
  Lublin = 'Lublin',
  Bialystok = 'Białystok',
  Katowice = 'Katowice',
  Czestochowa = 'Częstochowa',
  Olsztyn = 'Olsztyn',
  ZielonaGora = 'Zielona Góra',
}

export const cityCategoryCollection = [
  'Warszawa',
  'Kraków',
  'Łódź',
  'Wrocław',
  'Poznań',
  'Gdańsk',
  'Sopot',
  'Gdynia',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Białystok',
  'Katowice',
  'Częstochowa',
  'Olsztyn',
  'Zielona Góra',
];
