export enum CityCategoryEnum {
  All = 'All',
  Warszawa = 'Warszawa',
  Krakow = 'Kraków',
  Lodz = 'Łódz',
  Wroclaw = 'Wrocław',
  Poznan = 'Poznań',
  Gdansk = 'Gdańsk',
  Sopot = 'Sopot',
  Gdynia = 'Gdynia',
  Szczecin = 'Szczecin',
  Bydgoszcz = 'Bydgoszcz',
  Lublin = 'Lublin',
  Bialystok = 'Białystok',
  Katowice = 'Katowice',
  Czestochowa = 'Częstochowa',
  Olsztyn = 'Olsztyn',
  ZielonaGora = 'Zielona Góra',
}

export const cityCategoryCollection = [
  'All',
  'Warszawa',
  'Krakow',
  'Lodz',
  'Wroclaw',
  'Poznan',
  'Gdansk',
  'Sopot',
  'Gdynia',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Bialystok',
  'Katowice',
  'Czestochowa',
  'Olsztyn',
  'ZielonaGora',
];
